### ISSUE TITLE
Pas d'export sur un serveur public

### ISSUE THREAD

**Issue by ghost** [3rd-KaTZe/Export_DCS_V2#2]
Un hook lua désactivé quand export=false dans la config du serveur ?

**Comment by ghost** [comment]
Confirmé sur virtualacrobatics

**Comment by ghost** [comment]
Erreur trouvée: LoGetIndicatedAirSpeed()

Les exports exportent FC3 par défaut. Cette fonction renvoie 'nil' quand tu n'es pas dans un avion FC3. Il va falloir encapsuler tout ça, je teste et je reviens.

**Comment by ghost** [comment]
corrigé

**Comment by ghost** [comment]
Pas de retour Pit en mutli seulement.

Un clic dans le KAtzePit effectue la commande, mais les données ne vont de pas de SIOC au KatzePit.

**Comment by etcher3rd** [comment]
Confirmé: SIOC ne fonctionne pas si les exports du serveur sont désactivés
